import multiprocessing
import time
import os, sys
current_directory = os.path.dirname(os.path.abspath(__file__))
tasks_code_path = os.path.join(current_directory, 'tasks')
sys.path.append(tasks_code_path)

##IMPORT TASKS
from Task_1_nasa_nrt_daily_cholorophyll import nasa_nrt_daily_choloropphyll as Task1
from Task_2_nasa_nrt_monthly_chlorophyll import nasa_nrt_monthly_choloropphyll as Task2
from Task_3_noaa_nrt_daily_coral_bleaching import noaa_nrt_daily_coral_bleaching as Task3
from Task_4_noaa_forecast_monthly_coral_bleaching import noaa_forecast_monthly_coral_bleaching as Task4
from Task_5_noaa_hindcast_daily_sst_anomalies import noaa_hindcast_daily_sst_anomalies as Task5
from Task_6_noaa_nrt_daily_sst_anomalies import noaa_nrt_daily_sst_anomalies as Task6
from Task_7_noaa_hindcast_monthly_ersst import noaa_nrt_daily_sst_anomalies as Task7
from Task_8_bom_forecast_monthly_sst import bom_forecast_monthly_sst as Task8
from Task_9_bom_forecast_monthly_ssh import Task_9_bom_forecast_monthly_ssh as Task9
from Task_10_cmems_nrt_daily_ssh import cmems_nrt_daily_ssh as Task10
from Task_11_bom_forecast_seasonal_sst import bom_forecast_seasonal_sst as Task11
from Task_12_bom_forecast_hourly_ww3 import bom_forecast_hourly_ww3 as Task12

Task11()
